import turtle
t = turtle.Turtle()
screen = turtle.Screen()
screen.title("Heart")
screen.bgcolor("black")
t.color("red")
t.up()
t.goto(0,-50)
t.down()
t.begin_fill()
t.fillcolor("red")
t.left(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
turtle.done()